version: '3'

services:
  web:
    image: nodejs-angular-starter
    build:
      context: .
      args:
        - NODE_ENV
    environment:
      - NODE_ENV
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - "~/web_mongo:/data/db"

  # Test database used for running tests only
  test-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27019:27017

